bot_token = ""
opencode_port = 5000
log_level = "debug"
summarizer_instruction = "Generate a git commit message in conventional commit format. The first line should be in the format 'type(scope): description'. Follow with a bullet-point list of key changes made in the session. Keep the entire message concise."

[[model]]
provider_id = "openrouter"
model_id = "z-ai/glm-4.5"

[[model]]
provider_id = "opencode"
model_id = "grok-code"

[[repository]]
path = "/path/to/repository"
name = "repository_name"
