bot_token = ""
opencode_port = 5000
log_level = "debug"

[[model]]
provider_id = "openrouter"
model_id = "z-ai/glm-4.5"

[[model]]
provider_id = "opencode"
model_id = "grok-code"

[[repository]]
path = "/path/to/repository"
name = "repository_name"
