bot_token = ""
opencode_port = 5000
log_level = "debug"
summarizer_instruction = "Summarize current session messages into a single concise summary for git commit messages under 50 characters. Do not exceed the limit, prefer brevity over detail. "

[[model]]
provider_id = "openrouter"
model_id = "z-ai/glm-4.5"

[[model]]
provider_id = "opencode"
model_id = "grok-code"

[[repository]]
path = "/path/to/repository"
name = "repository_name"
