version: '3.8'

services:
  codesession:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codesession
    restart: unless-stopped
    volumes:
      # Persistent storage for sessions and worktrees
      - ./data/sessions:/app/.sessions
      - ./data/worktrees:/app/.worktrees
      # Configuration file - copy from config.example.toml and customize
      - ./config.toml:/app/config.toml:ro
    networks:
      - codesession-net

networks:
  codesession-net:
    driver: bridge

volumes:
  sessions_data:
  worktrees_data: