version: '3.8'

services:
  codesession:
    image: ghcr.io/famasya/codesession:latest
    container_name: codese
    restart: always
    volumes:
      # Persistent storage for sessions and worktrees
      - sessions_data:/app/.sessions
      - worktrees_data:/app/.worktrees
      # Configuration file - ensure config.toml exists with bot token and settings
      - ./config.toml:/app/config.toml:ro
    networks:
      - codesession-net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  codesession-net:
    driver: bridge

volumes:
  sessions_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SESSIONS_DATA_PATH:-./data/sessions}
  worktrees_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORKTREES_DATA_PATH:-./data/worktrees}
