version: '3.8'

services:
  codesession:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codesession
    restart: unless-stopped
    volumes:
      # Persistent storage for sessions and worktrees
      - ./data/sessions:/app/.sessions
      - ./data/worktrees:/app/.worktrees
      # Configuration file - copy from config.example.toml and customize
      - ./config.toml:/app/config.toml:ro
    networks:
      - codesession-net
    
  # Optional: Add a volume backup service for important data
  backup:
    image: alpine:latest
    container_name: codesession-backup
    profiles:
      - backup
    volumes:
      - ./data/sessions:/backup/sessions:ro
      - ./data/worktrees:/backup/worktrees:ro
      - ./backups:/output
    command: |
      sh -c "
        echo 'Creating backup...'
        tar czf /output/backup-$$(date +%Y%m%d-%H%M%S).tar.gz -C /backup .
        echo 'Backup completed'
      "

networks:
  codesession-net:
    driver: bridge

volumes:
  sessions_data:
  worktrees_data: