# Test configuration for codesession bot
log_level = "error"

[discord]
token = "test-discord-token-123456"
guild_id = "987654321"

[opencode]
endpoint = "http://localhost:8080"

[[repositories]]
name = "test-repo-1"
path = "/tmp/test-repo-1"

[[repositories]]
name = "test-repo-2"
path = "/tmp/test-repo-2"

[[models]]
name = "gpt-4-test"
provider = "openai"
model = "gpt-4"
api_key = "test-openai-key"
provider_id = "openai"
model_id = "gpt-4"

[[models]]
name = "claude-3-test"
provider = "anthropic"
model = "claude-3-sonnet"
api_key = "test-anthropic-key"
provider_id = "anthropic"
model_id = "claude-3-sonnet-20241022"

[commit_summarizer]
provider = "openai"
model = "gpt-3.5-turbo"
api_key = "test-summarizer-key"
custom_instructions = "Generate concise commit messages for test scenarios."