name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Get dependencies
      run: go mod download

    - name: Build for macOS Apple Silicon
      run: |
        GOOS=darwin GOARCH=arm64 go build -o codesession-darwin-arm64 .
        
    - name: Build for macOS Intel
      run: |
        GOOS=darwin GOARCH=amd64 go build -o codesession-darwin-amd64 .
        
    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o codesession-linux-amd64 .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Docker Image
          ```bash
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ```
          
          ## Binaries
        files: |
          codesession-darwin-arm64
          codesession-darwin-amd64
          codesession-linux-amd64
