name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Get dependencies
      run: go mod download

    - name: Build for macOS Apple Silicon
      run: |
        GOOS=darwin GOARCH=arm64 go build -o codesession-darwin-arm64 .
        
    - name: Build for macOS Intel
      run: |
        GOOS=darwin GOARCH=amd64 go build -o codesession-darwin-amd64 .
        
    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o codesession-linux-amd64 .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        name: Release ${{ github.ref_name }}
        files: |
          codesession-darwin-arm64
          codesession-darwin-amd64
          codesession-linux-amd64
